### ISSUE TITLE
[Repositories] Update shells repo to 15.2

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-installer#1]
It appears that the `shells` repo needed for Shellinabox is now available for Leap 15.2 (x86_64 only, though), so we might be able to update the current one we use (Leap 15.1):
http://download.opensuse.org/repositories/shells/openSUSE_Leap_15.2/

The shellinabox version appears identical:

#### Leap 15.2
http://download.opensuse.org/repositories/shells/openSUSE_Leap_15.2/x86_64/shellinabox-2.20+git.1548649128.4f0ecc3-lp152.3.1.x86_64.rpm.mirrorlist

#### Leap 15.1
http://download.opensuse.org/repositories/shells/openSUSE_Leap_15.1/x86_64/shellinabox-2.20+git.1548649128.4f0ecc3-lp151.3.1.x86_64.rpm.mirrorlist

**Comment by phillxnet** [comment]
@FroggyFlox Thanks. I'll have a quick look at this one so I can test the new repo against our back-end pr testing setup on something that is hopefully fairly straight forward.

**Comment by phillxnet** [comment]
Shells shellinabox OBS page for references:
https://build.opensuse.org/package/show/shells/shellinabox
