### ISSUE TITLE
Explicit use of pip3 in boxbuild instructions

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#101]
Thanks to @Hooverdan96 for reporting on the forum a pip python2 default issue in our boxbuild instructions. It is proposed that we specify the use of pip3 as some OS's still have a pip / pip3 split for python2 / python3 relevance.

Forum reference: https://forum.rockstor.com/t/building-opensuse-installer-with-kernel-backport-4-1-0-0-not-successfully-installing-solved/8295/4

**Comment by phillxnet** [comment]
It may be that some distros do not have a pip3, we can additionally have a note to this effect.

**Comment by Hooverdan96** [comment]
@phillxnet, I can create a draft of the doc changes, and then we can expand/change as necessary. For me, the virtual environment had actually both pip and pip3 available in the directory it creates during the first command, but you are right, that might be different for other distros.

**Comment by Hooverdan96** [comment]
Take a look at the pull request #102  contents. If this is too verbose, and should just have a quick mention about pip vs. pip3 I can compress.
