### ISSUE TITLE
Proposal to add wget to our included packages

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#133]
Currently, for development purposes, the only package not pre-installed in the resulting image/install, either via explicit kiwi-ng config or via the 'rockstor' package's dependencies is wget. Given we currently already pre-install such developer focused nice-to-haves as nano, it is proposed that we install this final package 'hurdle' by way of a further additional explicit inclusion in the installer config. It does not represent a package dependency as such given there is no non-developer orientated requirement function wise within the package. Hence the suggestion we add it as a convenience as per our nano inclusion.

This is in-keeping with easing user on-boarding regarding development involvement.

**Comment by FroggyFlox** [comment]
Thanks for that one, @phillxnet !
I actually started creating that very issue the other day but changed my mind. I'm still undecided but we might as well include it indeed.

**Comment by phillxnet** [comment]
@FroggyFlox Yes, I was back and forth on this when last cleaning up the installer package list, and updating the package dependencies. But it's now one straggler and nano + friends (i.e. htop) are already included in the installer.

I think the numb of it is that we are predominantly DIY friendly, and thus have system tools a-plenty. This way at least folks can move to a development setup, from a pre-build installer, with zero additional packages which is neat.
