### ISSUE TITLE
Include additional kernel-firmware packages

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#134]
As per forum member stitch10925's findings in the referenced thread, we likely have need to include additional (or all) available kernel-firmware files. The current proposal is for the addition of:
```
kernel-firmware-intel
kernel-firmware-network
kernel-firmware-platform
```

Currently we have the following packages included in this area:
https://github.com/rockstor/rockstor-installer/blob/297f02ba2f70577f15f27699c319b6118c080bbb/rockstor.kiwi#L420-L421

and the following relevant comment:

https://github.com/rockstor/rockstor-installer/blob/297f02ba2f70577f15f27699c319b6118c080bbb/rockstor.kiwi#L449-L450

Due to our more recent move to a Poetry based build in our 'rockstor' package, we have many more additional 'developer' packages that are dependencies of the 'rockstor' package (due to our building of dependencies upon rpm install). This in turn makes for a significantly larger installer image (around 900MB). As such these firmware options now represent a smaller percentage increase in the resulting installer. 

Further exploration of the degree to which the firmware packages will expand the image can be done under this issue. But give we are in the  'appliance' arena the utility of out-of-the-box function trumps all but excessively large, or mostly no-longer-relevant firmware additions.

Referenced forum issue: https://forum.rockstor.com/t/solved-missing-network-card-drivers-intel-i225-v/8624/15

**Comment by Stitch10925** [comment]
Please note that there is also:

- kernel-firmware-marvell => Marvell network drivers (quite popular chipset)
- kernel-firmware-qcom => Qualcom device drivers (could be network)
- kernel-firmware-qlogic => QLogic network drivers (unknown to me)
- kernel-firmware-chelsio => Chelsio network drivers (also unknown to me)

So I'm wondering if maybe it would be a good approach to not include these firmware packages directly in the build, but do a detection of hardware manufacturer (intel, qualcom, marvell, etc ...) and then pull the required firmware packages? This might require the addition of lspci and lshw.

I'm fairly new to Linux, so maybe this is not feasable, but it was a thought I wanted to throw out there.

**Comment by Stitch10925** [comment]
So... I just realized the chicken-and-egg situation my proposal would cause, because how can you pull firmware packages for network drivers if you don't have a network connection?

So, please ignore my idea. It's obviously flawed...

**Comment by phillxnet** [comment]
For the proposed we have, via `rpm -qi package-name`

License     : SUSE-Firmware AND GPL-2.0-only AND GPL-2.0-or-later AND MIT

on all of:

kernel-firmware-intel 2.5 MiB
kernel-firmware-marvell 2.3 MiB
kernel-firmware-network 3.6MiB
kernel-firmware-platform 1.6 MiB
kernel-firmware-qlogic 12.8MiB
kernel-firmware-chelsio 2.9 MiB

@Stitch10925 I'm skipping:

kernel-firmware-qcom  20.2 MiB (so a little shy, size wise, of all the above added up)

for now as unsure if these are just wifi, plus we have had no requests for these yet. But all the others you mentioned I'm popping in vi a pull request against this issue to hedge our bets. But it remains to be seen if the build still works.

Thanks for pointing out the others. Best if we can stick to just devices relevant to us (net and storage, usb likely) as the all firmware package was massive last time I tried it.
