### ISSUE TITLE
"Leap15.3.ARM64EFI" profile failure

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#138]
We have a non existent repo breaking our "Leap15.3.ARM64EFI" profile installer build.
This may relate to the EOL status of openSUSE Leap15.3.
A possible fix is the outstanding issue "Remove Leap 15.3 profiles" #126

```
[ ERROR   ]: 11:16:24 | KiwiUriOpenError: http://download.opensuse.org/repositories/home:/mcbridematt/openSUSE_Leap_15.3/: 404 Client Error: Not Found for url: http://download.opensuse.org/repositories/home:/mcbridematt/openSUSE_Leap_15.3/
```
The failing repo is solely concerned with the Ten64 drivers provided by @mcbridematt .

@mcbridematt do you have any info on the upstream inclusion of these driver re say 15.4/15.5/Tumbleweed ?
As I remember you were working towards this.
My apologies for not keeping up with progress in this area.

For now  I will likely just remove this repo reference to re-enable this profile.

**Comment by phillxnet** [comment]
https://github.com/rockstor/rockstor-installer/blob/ccaf93952cf5463357c919ed37a4e73514ed6908/rockstor.kiwi#L356-L361

**Comment by mcbridematt** [comment]
Doh - I thought I told OBS to defer deletion for those repos as I knew they were being used in Rockstor. Looks like I missed the Leap15.3 one.

But Leap15.4 and later will generally run fine on the Ten64 without any extra packages. Leap15.3 got tangled in a [openSUSE kernel bug](https://forum.traverse.com.au/t/bare-metal-rockstor-issue-support-help/318/4) and won't boot on the Ten64 anymore.

The sensor drivers haven't been upstreamed yet (need a big rewrite). I believe most of the Ten64 Rockstor users (myself included) run Rockstor as a VM anyway.

**Comment by phillxnet** [comment]
@mcbridematt Thanks for the update. Yes the OBS auto removal stuff, especially when one manages a few OS targets, can be tricky. No worries.

> But Leap15.4 and later will generally run fine on the Ten64

Re your appliance store reference:
Note that as of yesterday we have rebuilt and uploaded new 4.5.8-0 installers.
Also note that we have a space issue on our downloads server so I currently have to delete older installers (I know... in time!).
My apologies if this ends up messing with some of your links.
Can I delete the now very old 15.2 installer without affecting any of your setups/systems/clients?

Hoping to add a 15.5 target soon by the way.

Nice, and rather unfortunate bug report that!

**Comment by mcbridematt** [comment]
Hi @phillxnet 

>  Note that as of yesterday we have rebuilt and uploaded new 4.5.8-0 installers.

Thanks for letting me know, I've updated the entry to point to the 4.5.8-0 image.

>  Can I delete the now very old 15.2 installer without affecting any of your setups/systems/clients?

Yes, not aware of anyone using it, or any reason to use it with 15.4 builds now available.
