### ISSUE TITLE
[warning] root subvolume is not explicitly defined

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-installer#147]
In current build of Leap 15.5 profile, I see the following warning:
```
[ WARNING ]: 00:40:17 | Implicitly creating root volume
[ WARNING ]: 00:40:17 | --> Future versions of kiwi will not do this anymore
[ WARNING ]: 00:40:17 | --> Please specify btrfs_root_is_subvolume true|false
```

This is with kiwi running in the boxbuild method:
```
$ pip show kiwi
Name: kiwi
Version: 9.25.18
Summary: KIWI - Appliance Builder (next generation)
Home-page: https://osinside.github.io/kiwi
Author: Marcus Schaefer
Author-email: ms@suse.com
License: GPLv3+
Location: <path-to>/rockstor-installer/kiwi-env/lib/python3.11/site-packages
Requires: docopt, lxml, PyYAML, requests, simplejson
Required-by: kiwi-boxed-plugin
```

After a brief look, it seems to be a newer option:
- introduced at https://github.com/OSInside/kiwi/pull/2324
- documented at https://osinside.github.io/kiwi/image_description/elements.html

This seems to be something to keep an eye on as it may be **required** if future versions of kiwi (kiwi 10 maybe?).

**Comment by phillxnet** [comment]
Confirming that our current config with kiwi-ng 10.0.13, for profile Leap15.6.x86_64;
and a lightly modified config with kiwi-ng 10.1.18,
still results in the following warnings:

```
[ WARNING ]: 12:25:20 | Implicitly creating root volume
[ WARNING ]: 12:25:20 | --> Future versions of kiwi will not do this anymore
[ WARNING ]: 12:25:20 | --> Please specify btrfs_root_is_subvolume true|false
```

**Comment by phillxnet** [comment]
What we may need, and that needs testing to ensure this does not modify our existing btrfs setup, is likely:

##  <preferences><type>

We currently have for example:
https://github.com/rockstor/rockstor-installer/blob/ccc1b55ae99942fbb29b7c6d1e5b62c3fa237600/rockstor.kiwi#L51

And we likely need another option in there:

```
btrfs_root_is_snapshot="true"
<type image="oem" primary="true" initrd_system="dracut" filesystem="btrfs" fsmountoptions="noatime" firmware="efi" installiso="true" kernelcmdline="nomodeset plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G" bootpartition="false" devicepersistency="by-label" btrfs_root_is_snapshot="true" btrfs_root_is_subvolume="true" btrfs_quota_groups="false" efipartsize="64">
```

**Comment by phillxnet** [comment]
From: https://osinside.github.io/kiwi/image_description/elements.html#image

We have the docs for kiwi-ng stating for:

## btrfs_root_is_subvolume=”true|false”:
https://osinside.github.io/kiwi/image_description/elements.html#image

> By default the creation of a toplevel volume is set to: true

So setting this to "true" should be explicitly adopting what we are already seeing with our existing config.

**Comment by phillxnet** [comment]
@Hooverdan96 No worries at all, I was to tent to this today. But via your indicated efforts I can now move to testing those, I'll edit your PR to be a fix for this issue.
