### ISSUE TITLE
Consider the openSUSE-repos package

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-installer#151]
If my memory is correct, this was brought up by @Hooverdan96 quite some time ago (my apologies for not finding that mention).

The upstream openSUSE repos are now defined in a simple manner using the **openSUSE-repos** package. This is available in Leap 15.5 and Tumbleweed, so we might want to consider that once we dropped our Leap 15.4 profiles.

This would allow to drastically simplify the definition of repos in our `rockstor.kiwi` file but we may need to verify:
- that it would still be compatible with kiwi-ng
- that it wouldn't interfere with what rockstor-core needs to see as listed repositories. I don't think it would be a problem, but I believe the `opensuse-repos` package would install the upstream repos *as a zypper service*

References:
https://github.com/openSUSE/openSUSE-repos

or from https://en.opensuse.org/SDB:System_upgrade#Note_about_ports_(non_intel_architectures)

> Users can install [openSUSE-repos](https://software.opensuse.org/package/openSUSE-repos-Leap) that always provides up to date repository definitions. Package was introduced in Leap 15.5, Tumbleweed and Leap Micro 5.4. Users with older releases will need to download it from software.opensuse.org manually.

**Comment by Hooverdan96** [comment]
@FroggyFlox nice! I think you were referring to this comment earlier this year:

https://github.com/rockstor/rockstor-core/issues/2501#issuecomment-1443921640

**Comment by phillxnet** [comment]
Re:

> once we dropped our Leap 15.4 profiles.

Noting that this is now the case via: "Remove Leap 15.4 profiles #157" #163

**Comment by phillxnet** [comment]
I'm not entirely sure how this will play with our requirement during build. From my initial read I see that the package adds/redefines repos on the host. But when building images our kiwi-ng config provides the repos required for the packages we stiplulate, and we then add those same repositories to our resulting install via the "imageinclude" option in our repo definitions:

```
    <repository type="rpm-md" alias="Leap_15_6" imageinclude="true" profiles="Leap15.6.x86_64,Leap15.6.RaspberryPi4,Leap15.6.ARM64EFI">
        <source path="obs://openSUSE:Leap:15.6/standard"/>
    </repository>
```

Mostly anyway. But adding this repos-adding package to the to-be-installed image doesn't make those packages available during the build: where we need those repos to ensure we have access to the packages they contain.

**Comment by phillxnet** [comment]
Re:
> Mostly anyway.

We add for installer-build-time-only such repos as the following:
```
    <repository type="rpm-md" alias="repo-backports-update" profiles="Leap15.6.x86_64,Leap15.6.RaspberryPi4,Leap15.6.ARM64EFI">
        <source path="https://download.opensuse.org/update/leap/15.6/backports/"/>
    </repository>
```
That came about around 15.3/15.4 via a package addition. Adding them in kiwi-ng config for build time only meant our resulting images included the updates they afforded. Making them way more up-to-date.

**Comment by phillxnet** [comment]
Re:

> * but I believe the `opensuse-repos` package would install the upstream repos _as a zypper service_

and my follow-up comments here re:

> From my initial read I see that the package adds/redefines repos on the host. But when building images our kiwi-ng config provides the repos required for the packages we stiplulate, and we then add those same repositories to our resulting install via the "imageinclude" option

I'm moving to close this issue as I think it would add, rather than remove complexity as it could invalidate / duplicate our existing treatment of these repos, i.e. we likely name them differently but consistently over time. And our `zypper dup ...` based in-place update how-to would also be affected by this change.

Closing for now as we need these repos up-front during build time to have access to their updates. Plus we are now on the possible last traditional Leap variant: where - there after - all this may change.

Feel free to re-open if some testing time is available and a proof of function involving a pull request is presented.
