### ISSUE TITLE
kiwi-ng version 10.0.2 requires <bootlader> definition to be subset to <type> tag

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-installer#159]
Not sure, when/how that change occurred, but during a recent run using kiwi-ng (after update to version 10.2.5) the built failed due to the bootloader name definition being inside the definition of the `<preference><type>` tag.

Apparently, according to this [link](https://osinside.github.io/kiwi/image_description/elements.html#preferences-type-bootloader)

this now resides within the <type> tag but has its own sub-tag, i.e. `<preference><type><bootloader>`

After separating the bootloader out to test this out, i.e. moving from:

```xml
        <type
                image="oem"
                primary="true"
                initrd_system="dracut"
                filesystem="btrfs"
                fsmountoptions="noatime"
                bootloader="grub2"
                firmware="efi"
                installiso="true"
                kernelcmdline="nomodeset plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G"
                bootpartition="false"
                devicepersistency="by-label"
                btrfs_root_is_snapshot="true"
                btrfs_quota_groups="false"
                efipartsize="64"
        >
```
to
```xml
        <type
                image="oem"
                initrd_system="dracut"
                filesystem="btrfs"
                fsmountoptions="noatime,compress=lzo"
                firmware="efi"
                kernelcmdline="plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G earlycon"
                bootpartition="false"
                devicepersistency="by-uuid"
                btrfs_root_is_snapshot="true"
                btrfs_quota_groups="false"
                efipartsize="64"
                format="qcow2"
        >
            <bootloader name="grub2"/>
```

The build proceeds without issue.

@phillxnet, @FroggyFlox if you're in agreement (don't know if there is a difference using the kiwi-box-plugin, I am running on a dedicated OpenSUSE installation), I can submit a pull request correcting the above situation. Let me know.

**Comment by phillxnet** [comment]
@Hooverdan96 Nice find. Yes a pull request would be most welcome. We likely also need to update the Readme to indicate a minimum version of Kiwi-ng once these changes are in effect. Hopefully it won't break anything along the way.

**Comment by Hooverdan96** [comment]
@FroggyFlox, hah, good point. I was experiencing this on a TW base system, so yes, TW already has it. I have not checked the Leap version yet. Let me do that before anything else.

**Comment by Hooverdan96** [comment]
So, I checked. On my 15.5 version 9.x is installed. Checking out the appliance repo for 15.5 here:

https://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_15.5/x86_64/

it already gives version 10.03. when I force the install (since zypper indicates there is an update candidate), I seem to have to also install python >= 3.9 (I chose to go to 3.11 to check this out), since that's a dependency of kiwi 10.x

Since I've had that LEAP install for a while and mucked around with it, I don't know whether that's preventing it from installing the 10.x version or not. Unless one of you has a pristine one and can check, I will have to create a new VM with a fresh install and check what following the installations in the Readme will yield.

Since the 9.x docs have been replaced with 10.x docs on the official https://osinside.github.io/kiwi/ website, I'd suggest that we adapt the installation instructions (if necessary) from the obs repository to ensure that 10.x is installed. What do you think?

**Comment by Hooverdan96** [comment]
Additional information:
fresh Leap 1.5. install, python3 version is 3.6.x

Validated that, while documentation still states a minimum of 3.6 requirement for the kiwi install, the pyproject.toml stipulates greater or equal 3.9:

https://github.com/OSInside/kiwi/blob/c943aa15f64670f6ffdcc2b9381a33d84dfece71/pyproject.toml#L51-L58

After installing python 3.11 and creating a virtual environment based on that version (instead of 3.6) the kiwi and box plugin installation yielded the 10.x version.

So, my suggestion is to update the documentation (aside from the update to the `rockstor.kiwi`) as @phillxnet already hinted at with the higher python version called out (I think, in this case the only note about 2.x python support is probably highlighting that kiwi definitely needs the python 3.9+ to get the most up-to-date version.
