### ISSUE TITLE
Tailscale repo signature verification failed

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#171]
After having fully update our backend OS and during the ongoing move to Kiwi-NG V10 I'm now seeing the following with our treatment of Tailscale's 15.5 repo signature verification:
```
[ ERROR   ]: 10:33:20 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: Repository 'tailscale-stable' is invalid.
[tailscale-stable|https://pkgs.tailscale.com/stable/opensuse/leap/15.5/x86_64] Valid metadata not found at specified URL
History:
 - Signature verification failed for repomd.xml

Please check if the URIs defined for this repository are pointing to a valid repository.
Some of the repositories have not been refreshed because of an error.
```

This was working previously on the same profile (15.6) tested in the following draft PR coment: https://github.com/rockstor/rockstor-installer/pull/167#issuecomment-2069084725

---
Given the difficulties experienced with Tailscales repos: see the following PR where we provisionally introduced them:

Pre-install Tailscale #142 #158

And the related issue where @FroggyFlox had such issues in working around their repo 'type':

Pre-install Tailscale #142

And that we have had nothing like this with any of our other repos (all native admittedly) I'm now strongly leaning towards dropping the pre-installed Tailscale stance. They do install just dandy via their own instructions: but are definitely not kiwi-ng friendly and are holding up our installer releases as a result. This is not likely to change give our experience to date. And our current addition re working around their repo format is as-yet still incomplete.

**Comment by FroggyFlox** [comment]
Sounds good to me and will greatly simplify our kiwi file as a result too. We can work on a solution to install the repo and package in rockstor-core when one configures the service, maybe.

**Comment by phillxnet** [comment]
Just re-tested with kiwi-ng v10.0.13, released 30/04/24 (yesterday) and this situation persists. Moving to remove our as yet still incomplete attempt to pre-install tailscale, and it's associated stable repo, via our kiwi-ng config.
```
KIWI (next generation) version 10.0.13
...
[ ERROR   ]: 10:10:22 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: Repository 'tailscale-stable' is invalid.
[tailscale-stable|https://pkgs.tailscale.com/stable/opensuse/leap/15.5/x86_64] Valid metadata not found at specified URL
History:
 - Signature verification failed for repomd.xml
Please check if the URIs defined for this repository are pointing to a valid repository.
Some of the repositories have not been refreshed because of an error.
: 
program finished with exit code 1
```
