### ISSUE TITLE
Vagrant boxes not mounting shared folder

### ISSUE THREAD

**Issue by mikemonkers** [rockstor/rockstor-installer#38]
As per this thread: https://forum.rockstor.com/t/problem-building-rockstor-4-with-vagrant/7639 the specified vagrant box for the installer is failing to mount shared folders.

eg.

![](https://forum.rockstor.com/uploads/default/original/2X/d/d39b68e59bf24e430eeda61b344d611cb66a2c17.png)

**Comment by mikemonkers** [comment]
It would seem that updates to the Official OpenSUSE vagrant box has introduced issues with the virtualbox guest additions .

Pinning the version of the official opensuse VM box image to version 15.2.31.328 the mounting works.

This can be done as follows (ignore the above exploratory findings):

            v.vm.box = 'opensuse/Leap-15.2.x86_64'
            v.vm.box_version = "15.2.31.328"
It would seem that the versions after this include a broken virtual-box guest additions in the opensuse repo. (a zipper upgrade breaks the image version above).

However, this image seems to break a bunch of kiwi dependences including:

qemu-img
sgdisk

I’ll raise a PR with the change back to the bento box in the meantime, but do these broken dependencies ring a bell to anyone?

---
Reverting to the box 'bento' box restores functionality for now:
```
#             v.vm.box = 'opensuse/Leap-15.2.x86_64'
            v.vm.box = 'bento/opensuse-leap-15'
```

**Comment by FroggyFlox** [comment]
Thanks a lot for this nice find!


> do these broken dependencies ring a bell to anyone?

Maybe similar to: https://github.com/OSInside/kiwi/issues/1707
I unfortunately can't explore further at the moment but that might help... They've done a lot of work updating the `kiwi-systemdeps` lately but I'm not sure they're already shipped in the kiwi package you have. It might be something to explore as well.
