### ISSUE TITLE
Pi4 profile currently broken

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#44]
Thanks to forum member ktraglin for reporting the following broken Pi4 profile: "Leap15.2.RaspberryPi4". 

> Using Rockstor 4 Installer Recipe (RaspberryPi4) from github.
> 
> I’ve tried to build the installer using a fresh install of:
> openSUSE-Leap-15.2-ARM-JeOS-raspberrypi4.aarch64-2020.07.08-Build1.147.raw.xz
> 
> as well as a more recent one released this month:
> openSUSE-Leap-15.2-ARM-JeOS-raspberrypi4.aarch64-2020.07.08-Build1.163.raw.xz
> 
> I’ve tried several times to build the installer, but keep getting these errors:
> 
> [ INFO ]: Processing: [########################################] 100%
> [ ERROR ]: 21:53:04 | KiwiInstallPhaseFailed: System package installation failed:
> [ INFO ]: 21:53:04 | Cleaning up SystemPrepare instance
> localhost:~/rockstor-installer #
> 
> Some of the more interesting debug messages (from “/home/kiwi-images/build/image-root.log”) are as follows:
> 
> DEBUG: 23:03:59 | system: Resolving package dependencies…
> DEBUG: 23:03:59 | system: 2 Problems:
> DEBUG: 23:03:59 | system: Problem: nothing provides libc.so.6(GLIBC_2.33)(64bit) needed by shellinabox-2.20+git.1548649128.4f0ecc3-3.20.aarch64
> DEBUG: 23:03:59 | system: Problem: nothing provides libc.so.6(GLIBC_2.33)(64bit) needed by shellinabox-2.20+git.1548649128.4f0ecc3-3.20.aarch64
> DEBUG: 23:03:59 | system: Problem: nothing provides libc.so.6(GLIBC_2.33)(64bit) needed by shellinabox-2.20+git.1548649128.4f0ecc3-3.20.aarch64
> DEBUG: 23:03:59 | system: Solution 1: do not install shellinabox-2.20+git.1548649128.4f0ecc3-3.20.aarch64
> DEBUG: 23:03:59 | system: Solution 2: break shellinabox-2.20+git.1548649128.4f0ecc3-3.20.aarch64 by ignoring some of its dependencies
> DEBUG: 23:03:59 | system: Choose from above solutions by number or skip, retry or cancel [1/2/s/r/c/d/?] ( c ): c
> ERROR: 23:03:59 | KiwiInstallPhaseFailed: System package installation failed:
> localhost:~/rockstor-installer #

Please see the following forum thread for context:
https://forum.rockstor.com/t/beta-installer-build-fails-on-raspberrypi4/7710

Issue author has also seen this and the last know successful build of this profile within the closed beta builds of our ISO was at the release of the 4.0.5 rpm:
https://forum.rockstor.com/t/beta-built-on-opensuse-testing-channel-changelog/7097/12

**Comment by mcbridematt** [comment]
This one is likely on me as shellinabox is sourced from my OBS repo for arm64, due to the shells repo not having arm64 builds (I really should poke someone about that).

Let me see if I can update it..

**Comment by phillxnet** [comment]
@mcbridematt Thanks for taking a look at this. On initial inspection I didn't think it was related to your repos actually as the profile you contributed "Leap15.2.ARM64EFI" worked a treat still and built, as intended, in the last closed iso beta round I did for the 4.0.6 rpm release. It was only the Pi4 build that failed. But do please double check if you get the time as I've not managed to focus on this specific issue in a timely manner unfortunately.

At the time I wondered if something changed upstream in the interim between the build server doing the Leap15.2.ARM64EFI profile ISO and the slightly later attempt to do the Leap15.2.RaspberryPi4 profile iso. The two are pretty close really in dependencies, hence the surprise.

**Comment by mcbridematt** [comment]
The cause of this issue is that shellinabox is being pulled from the "openSUSE_Factory_ARM" repository for "shells" rather than mine as is the case for ARM64EFI.

As factory is now closer to Leap 15.3 than 15.2 the shellinabox package from Factory_ARM is no longer compatible.

I've asked nicely over at OBS if the shells project can add a Leap15.2 build cycle: https://build.opensuse.org/project/show/shells#comment-1441655

In the meantime, this will fix the RaspberryPi4 profile:

```
diff --git a/rockstor.kiwi b/rockstor.kiwi
index 2c52a2d..210f109 100644
--- a/rockstor.kiwi
+++ b/rockstor.kiwi
@@ -330,7 +330,7 @@ which includes aarch64 relevant content -->
     </repository>
     <!-- For Traverse Ten64 drivers -->
     <repository type="rpm-md" alias="mcbridematt" imageinclude="true"
-                profiles="Leap15.2.ARM64EFI">
+                profiles="Leap15.2.RaspberryPi4,Leap15.2.ARM64EFI">
         <source path="obs://home:mcbridematt/openSUSE_Leap_15.2/" />
     </repository>
     <packages type="image">
```
Technically we should drop the import for shells/openSUSE_Factory_ARM (under ``<!-- TODO: NOT YET AVAILABLE FOR LEAP15.2 aarch64 so use Factory_ARM source for now -->``) as well.

I can put a pull request in for this if ok, @phillxnet ?

**Comment by phillxnet** [comment]
@mcbridematt Thanks for looking into this.

> As factory is now closer to Leap 15.3 than 15.2 the shellinabox package from Factory_ARM is no longer compatible.

Yes that explains it perfectly, and well done on the upstream request. Lets hope that gets some attention.



> Technically we should drop the import for shells/openSUSE_Factory_ARM (under `<!-- TODO: NOT YET AVAILABLE FOR LEAP15.2 aarch64 so use Factory_ARM source for now -->`) as well.


Agreed. We could also add a note indicating our awaiting an official upstream build with your own as a placeholder.



> I can put a pull request in for this if ok, @phillxnet ?

That would be very much appreciated, thanks.

Let me know here if you end up out of time on this one and I'll complete as per your findings. Would be great to have the Pi4 profile working again.

**Comment by phillxnet** [comment]
@mcbridematt I'm currently working on this one so now worries.

Thanks for the initial investigation. I'll 'patch' for now using your repo while we await a response re you request for the upstream shells repo for the aarch64 architecture. Incidentally it looks like factory is now no longer close enough too Leap 15.3 either (glibc change). Been looking into this for my next issue in this repo after sorting this one.

**Comment by phillxnet** [comment]
@mcbridematt I'm assuming your packages are not reliant on the factory arm repo?

I'd like to remark out the following until we have a proper shells repo available:

https://github.com/rockstor/rockstor-installer/blob/master/rockstor.kiwi#L300-L304

But that will in turn remove factory arm from the Leap15.2.ARM64EFI profile which is also for your Ten64 platform.

Assuming prior factory arm repo was only for shellinabox and as glibc has now been updated there it's no good for us in Leap 15.2 or 15.3 profiles on aarch64.

From a recent pre-release 4.0.6-0 aarch64 rpm on Leap 15.3 beta using the factory arm repo for shellinabox:
```
Loading repository data...
Reading installed packages...
Resolving package dependencies...
Problem: nothing provides 'libc.so.6(GLIBC_2.33)(64bit)' needed by the to be installed shellinabox-2.20+git.1548649128.4f0ecc3-3.21.aarch64
 Solution 1: do not install rockstor-4.0.6-0.aarch64
 Solution 2: break shellinabox-2.20+git.1548649128.4f0ecc3-3.21.aarch64 by ignoring some of its dependencies
Choose from above solutions by number or cancel [1/2/c/d/?] (c): c
```
