### ISSUE TITLE
Add Leap 15.3 profile for x86_64 & Aarch64

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#46]
With the pending release of openSUSE Leap 15.3 (beta currently) the time is nigh for adding the relevant architecture profiles.

https://en.opensuse.org/openSUSE:Roadmap#Schedule_for_openSUSE_Leap_15.3

**Comment by phillxnet** [comment]
This issue is dependant on the outstanding removal of the now End-of-Life Leap 15.1 profile.

In order that we do not grow indefinitely we should prune regularly and in this case EoL status for the given OS looks like  the clear indicator. Our Leap 15.1 is also x86_64 only as it predated our move to supporting Arm64 profiles.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
@mcbridematt Sorry to both you but I think we are in need of a Leap 15.3 repo in your OBS drivers repo re Ten64 / ARM64EFI :
https://build.opensuse.org/project/show/home:mcbridematt
I've comment to this end here:
https://build.opensuse.org/project/show/home:mcbridematt#comment-1447259
That way I can hopefully add a full suite of 'Built on openSUSE' Leap 15.3 profiles:

- Leap15.3.x86_64
- Leap15.3.RaspberryPi4
- Leap15.3.ARM64EFI

via this issue and it's in-preparation pull request.

**Comment by mcbridematt** [comment]
@phillxnet I just added a 15.3 aarch64build for shellinabox.

https://build.opensuse.org/package/live_build_log/home:mcbridematt/shellinabox/openSUSE_Leap_15.3/aarch64

You can leave the other Ten64 packages commented out for now, they will be updated in due course.

**Comment by phillxnet** [comment]
@mcbridematt Thanks for the extra repo. As per the referenced commit we are moving to host the shellinabox from rockstor_home so the Ten64 drivers were the issue really.

> You can leave the other Ten64 packages commented out for now, they will be updated in due course.

OK, thanks. I'll take a took at this shortly and will likely just not add the new Leap 15.3.ARM64EFI profile to the specific Ten64 driver section. We can always follow this up once they are ready or deemed un-required. I'll add something to the Readme to indicate the Ten64 pending status re Leap 15.3 and these drivers.
