### ISSUE TITLE
BaseMount/BaseCleanMount functions are deprecated

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-installer#52]
This issue is a follow-up of #49 .

In our `config.sh`, we currently use the `BaseMount` and `BaseCleanMount`. As reported in the kiwi build log, however, these functions are now deprecated as this is now taken care of by kiwi-ng itself. This deprecation happened in October 2020:
https://github.com/OSInside/kiwi/pull/1597

> The above methods are obsolete since kiwi handles these mount/umount processes as part of the core builder code.

It thus seems we can safely remove them from our `config.sh`, as has been done in Leap15.3 JeOS kiwi-template:
https://build.opensuse.org/package/view_file/openSUSE:Leap:15.3/kiwi-templates-JeOS/kiwi-templates-JeOS.changes?expand=1

> -------------------------------------------------------------------
> Wed Sep  2 10:00:36 UTC 2020 - Fabian Vogt <fvogt@suse.com>
> 
> - Drop call of baseCleanMount, not necessary

and

> -------------------------------------------------------------------
> Wed Jan 20 14:56:24 UTC 2021 - Fabian Vogt <fvogt@suse.com>
> 
> - Actually drop the call of baseCleanMount

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for your continued diligence on this one. Nice for us to stick more closely with upstream Kiwi-ng changes here, and nice to be able to remove some more kipple.
