### ISSUE TITLE
Several functions used in config.sh will soon be deprecated upstream

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-installer#55]
Several of the convenience functions present in `config.sh`, including some that we currently use, have recently been deprecated:
https://github.com/OSInside/kiwi/pull/1833

From this PR, I identify only `suseImportBuildKey()` as being a function we currently use and that will be deprecated in a future kiwi-ng release. As the new code mentions, though, this seems to now be taken care by kiwi so we might be able to simply remove the call to `suseImportBuildKey` in our `config.sh`:

```shell
function suseImportBuildKey {
    deprecated "${FUNCNAME[0]}" <<- EOF
	This is done by kiwi at call time of zypper
	EOF
}
```
https://github.com/OSInside/kiwi/blob/c40f44d9f681f80449d088b18c1d3f3a2d4f3316/kiwi/config/functions.sh#L814-L818

**Comment by phillxnet** [comment]
@FroggyFlox Having a quick look at this one again and it seems there was a back-track on this. See:

"Re-add suseImportBuildKey": https://github.com/OSInside/kiwi/pull/1877

If my reading of this is correct we can close this issue as the function is not longer in the to-be-deprecated list?

**Comment by phillxnet** [comment]
Linking to the current code for this build-in:

https://github.com/OSInside/kiwi/blob/29b1fe0c53d9ca60afd3a871b9eab15f129fd6a2/kiwi/config/functions.sh#L157-L199

**Comment by FroggyFlox** [comment]
Oh good catch... You seem to be right, indeed.
Let's thus close this.
