### ISSUE TITLE
Building inside an lxc fails

### ISSUE THREAD

**Issue by rhewy** [rockstor/rockstor-installer#56]
Currently, I am attempting to build inside an openSuSe 15.2 lxc on proxmox.

A lot happens but fails looking for stdout.

Would this even be possible? Does the container need to ran as root (not unprivileged in promox speek)

Would a vm work?

Does the building OS have to be bare metal?

I read the readme but the term discrete OS puzzled me.

**Comment by phillxnet** [comment]
@rhewy Thanks for the report:

> A lot happens but fails looking for stdout.

This sounds like an issue with how proxmos is handling the standard out for kiwi-ng. It's a program that runs as root in the host OS and does quite a lot of fairly privileged stuff and rather assumes it has all writes to do all things, such as chroot etc. So not really sure but:

> Would a vm work?
Yes this is usually the easiest way to go, at least until we investigate the build-in vm capability within kiwi-ng referenced in the Readme (i.e. the "See: kiwi-ng's new boxbuild capability." ) and add the required kiwi-ng command option to invoke this. From a quick look at this capability, our build instructions predate this option, it's just a single addition option to the command we already have. This really does look like the way to go for us as then any linux install could to the build "natively". And the native bit is important as kiwi-ng temporarily reconfigures the hosts package manager to 'build' the resulting install. Hence the suggestion that a discreet (read dedicated) OS be used for this purpose. And this inflexibility is likely why the boxbuild capability was added to kiwi-ng in the first place.

> Does the building OS have to be bare metal?

No, VM is fine.

> I read the readme but the term discrete OS puzzled me.

Good point. I was trying in that terminology to capture, in a non tecnical term, the idea of a dedicated install; such as a VM. We should improve the text there. Suggestions / pull requests welcome as always. Thanks for the pointer.

Hope that helps.

Incidentally a better medium for this type of discussion is our forum:
https://forum.rockstor.com/
as there are now a number of forum members how have successfully built their own Rockstor 4 installers and shared their experience in how they got on. Don't think we have had a Proxmox hosted attempt thought.

Thanks for the report, much appreciated.

**Comment by rhewy** [comment]
I was able to build the iso using a 15.3 OpenSUSE VM on Proxmox.
SCP the iso from the vm to the host. 
Then use the iso to create a RockStor VM on Proxmox.

I would still need to pass through some drives from host to VM to build a "RAID".

You might be able to get it to work in a container but there are a few switches to throw and test.
https://forum.proxmox.com/threads/mount-via-loop-device-in-container.47398/

This workflow exposes where many containers tap out and a VM wins.

Does anyone want the iso?
