### ISSUE TITLE
Please make "<!-- Change to" consistent in rockstor.kiwi

### ISSUE THREAD

**Issue by KodyVB** [rockstor/rockstor-installer#58]
This is a minor issue, but almost tripped me up. In the instructions for editing rockstor.kiwi, it says to change any lines preceded by "<!-- Change to" but only the first line that needs to be changed has "<!-- Change to". The following four lines (52, 107, 158, and 459) have "<!--Change to" (missing the space between the - and C). When I opened it up in vim to make the changes, I searched for the entire string, and probably wouldn't have noticed there were lines left out if there were more than one entry to change from that search result.

**Comment by phillxnet** [comment]
@KodyVB Nice find. Thanks for report this. I'm afraid this anomaly is down to me. I had thought I'd cut and pasted from the original. Oh well, bit by bit.

**Comment by phillxnet** [comment]
I am currently working on this issue.
