### ISSUE TITLE
remove ipv6.disable=1 kernel option

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#74]
We have recently encountered at least a couple of failures related to our stance in disabling IPv6. The first and currently most significant was in a recent upstream docker update to version: 20.10.6
"Docker 20.10.6: all containers stopped and cannot start if ipv6 is disabled on host"
https://github.com/moby/moby/issues/42288
The second is in our ability to instantiate/configure, via the Web-UI, a teaming/bonding interface reported by forum member Emmanuel_perez in the following forum post:
"Issues when trying add Teaming to Rockstor network "
https://forum.rockstor.com/t/issues-when-trying-add-teaming-to-rockstor-network/7913

We originally disabled IPv6 via yast2 which in turn edits /etc/sysctl.conf file. But this, ironically now, in turn caused a docker and postfix issue:
https://github.com/rockstor/rockstor-core/issues/2139#issuecomment-592956225
when no IPv6 config was assigned/available to the loopback and ethernet interfaces and services still attempted to use them.
So we moved to disabling via the kernel command line and tweaked our postfix (email notifications) to use only IPv4.
See part of "[openSUSE] fix postfix config re ipv4, tlsmgr, & CA file settings. ...":
https://github.com/rockstor/rockstor-core/pull/2135
"Enforce "inet_protocols = ipv4" in postfix if a prior 'all' setting is found. This avoids postfix service failure on ipv4 only systems."

The original intention for our move to disable IPv6, system wide, was as follows, from: https://github.com/rockstor/rockstor-core/issues/2139#issuecomment-593116985

> [Our]  intention [in disabling IPv6 is down to:] ... our Web-UI can only configure for ipv4 so we should, with our appliance aim, ensure the entire system is only using ipv4. Otherwise there are network configurations at play that were not intended by our users. I had initially though that the Yast suggestion in the dev notes would be sufficient.

& from @tyukh in the same issue:

> Since I am not a maintainer, I can only give my opinion. IPv6 is not used, has not been tested, and is completely unsupported in Rockstor codebase. Because of this, enabled IPv6 can cause potential problems and strange behavior.
> For example, the configuration for a some service may have IPv6 settings (e.g. interface binding) that Rockstar does not expect and process.

However we now have complete dysfunction of Rock-ons (our docker based plugin system) due to the above sited upstream docker bug that has been acknowledged & fixed in the docker development team:
https://github.com/moby/moby/pull/42413
but not backported to our Leap 15.* base for a few weeks now. Likely as a default Leap install is not affected by this issue.

Docker 20.10.7 does now have this fix in place: https://docs.docker.com/engine/release-notes/#20107

But given we have the following very similar issue from dockers history (in 2016):
```
- Fixed a bug which prevents docker reload when host is configured with ipv6.disable=1 ([#21019](https://github.com/docker/docker/pull/21019))
```
We may well now be swimming against the tide and would be best advised to drop our non standard grub config which was not favoured at the time but found to be the only 'fix'. From: https://github.com/rockstor/rockstor-core/issues/2139#issuecomment-592951389

> I think I'd rather go the sysctl route as we already do some editing there in initrock I believe where as we currently don't mess with grub and I'd rather leave it that way if possible.

So we are left with the hard choice of removing our hard disable of IPv6 simply due to the repeat issues found in software we absolutely depend upon simply not any longer being familiar with OS's in our current state. And returning to our prior multi year setting of not disabling but also not configuring IPv6 at all. At least until we do add this non trivial capability anyway.

Comments and alternative options welcome.

**Comment by phillxnet** [comment]
I am currently preparing a pull request for this issue.

**Comment by joschi127** [comment]
:+1: for this

also see https://github.com/rockstor/rockstor-core/issues/2139#issuecomment-898961448

> This change causes the following error when installing latest Duplicati Rock-On:
> 
> ```
> docker: Error response from daemon: driver failed programming external connectivity on endpoint duplicati-lsio ...
> ... Error starting userland proxy: listen tcp6
> ```
> 
> When I re-enable ipv6 Duplicati is working fine.
