### ISSUE TITLE
Grant NetworkManager capabilities on teamd

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-installer#89]
Thanks to forum member smokku for highlighting this issue via support email. Network manager is unable to enact a team network setup due to a lack of capabilities on the teamd deamon. The suggested fix was as follows:

> I needed to create
> /etc/systemd/system/NetworkManager.service.d/caps.conf
> with the following contents:
> 
> [Service]
> CapabilityBoundingSet=CAP_CHOWN

It is proposed that we add this file to our root overlay (those files within our /root directory) so that Network manage is awarded these additional capabilities.

**Comment by phillxnet** [comment]
In an attempt to find collaborating information on this approach we have the following:
https://forums.opensuse.org/showthread.php/540345-network-teaming-problem

Where forums.opensuse.org user arvidjaar suggests:

> NetworkManger service runs with restricted capabilities and lacks CAP_CHOWN. As workaround you can create drop-in that adds CAP_CHOWN to CapabilityBoundingSet.
> 
> This is upstream problem and ideally should be reported and discussed upstream. You can open openSUSE bugreport, at least to solicit maintainer feedback.

The original reported, sky.x, (in Tumbleweed of Jun 2020) then opened the following bug report as suggested:

https://bugzilla.opensuse.org/show_bug.cgi?id=1172487

> Jun 03 14:45:36 nasserver NetworkManager[5366]: Unable to change  ownership of /run/teamd/ to teamd/daemon (Operation not permitted)

This bug takes an alternative approach in an upstream fix released to Tumbleweed:


> Otto Hollmann 2021-12-01 08:57:14 UTC
> Hello there, 
> I was focused on our internal bug and forget to update this one.
> 
> Issue is already fixed, see:
> > https://build.opensuse.org/request/show/929722
> 
> and available in tumbleweed.
> 
> 
> NetworkManager creates directory /run/teamd with root:root permission and teamd can not change it. So let's create this directory with proper permission using tmpfiles.d and adjust chown part in teamd to ignore chown failure if permissions are already set properly.
> 
> @First Last Please let me know if it resolve your problem and if this bug can be closed.

**Comment by FroggyFlox** [comment]
Nice find!
I was curious so I looked: I had an update for `libteamdctl0` on my Rockstor-4.0.9 built on openSUSE Leap 15.3:
```
buildvm:~ # zypper info libteamd*
Loading repository data...
Reading installed packages...


Information for package libteamdctl0:
-------------------------------------
Repository     : Update repository with updates from SUSE Linux Enterprise 15
Name           : libteamdctl0
Version        : 1.27-4.3.1
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 22.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : libteam-1.27-4.3.1.src
Summary        : Library for controlling the team network device daemon
Description    : 
    Linux kernel 3.3 and above offer a so-called "team" network driver -
    a lightweight mechanism for bonding multiple interfaces together.
    It is a userspace-driven alternative to the existing bonding driver.
```

Looking at `libteam-1.27-4.3.1.src` on OBS, it seems to be including that patch:
https://build.opensuse.org/package/view_file/SUSE:SLE-15:Update/libteam/libteam.changes?expand=1

**Comment by phillxnet** [comment]
@FroggyFlox Well done chasing that up. I had to step away for a bit so much appreciated.

From the sighted change request here: https://build.opensuse.org/request/show/929722
we have:

> Fix permission issue when running with NetworkManager (bsc#1185424)
> [+ better_handle_failures_to_chown.patch]

From you link we have:

> -------------------------------------------------------------------
> Fri Nov 12 12:47:52 UTC 2021 - Otto Hollmann <otto.hollmann@suse.com>
> 
> - teamd: better handle failures to chown(TEAMD_RUN_DIR) during
>   teamd_drop_privileges() (bsc#1185424) 
>    [+ better_handle_failures_to_chown.patch]

Shame we can't see the indicated SuSE issue:
https://bugzilla.opensuse.org/show_bug.cgi?id=1185424

And sure enough our 15.3 profile has this package version if freshly build.

And from an older installed instance with update we have:

```
rleap15-3:~ # rpm -q --changelog libteamdctl0 | head -n 10
* Fri Nov 12 2021 otto.hollmann@suse.com
- teamd: better handle failures to chown(TEAMD_RUN_DIR) during
  teamd_drop_privileges() (bsc#1185424)
  [+ better_handle_failures_to_chown.patch]

* Fri Jan 05 2018 jengelh@inai.de
- Drop /pkg/ subpart from includedir

* Wed Jan 03 2018 tchvatal@suse.com
- Remove defattr that is not really needed
```

However in our soon to be EOL 15.2 based profile the fix doesn't look to have arrived.
```
rleap15-2:~ # zypper up --no-recommends libteamdctl0
Loading repository data...
Reading installed packages...
No update candidate for 'libteamdctl0-1.27-lp152.4.7.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.
```
With:
```
rleap15-2:~ # rpm -q --changelog libteamdctl0 | head -n 10
* Fri Jan 05 2018 jengelh@inai.de
- Drop /pkg/ subpart from includedir

* Wed Jan 03 2018 tchvatal@suse.com
- Remove defattr that is not really needed
- Add condition around python bindings, they are really based on
  swig code that would need to be rewritten to support python3

* Wed Nov 22 2017 ndas@suse.de
- allow send_interface in dbus conf file for wicked.
```

**Comment by phillxnet** [comment]
@FroggyFlox I'll contact the reporter and point them to this issue. Closing for now as this looks very much like the original issue has been addressed but by directory treatment rather than additional privileges:

https://build.opensuse.org/request/show/929722

```
22+# Install /usr/lib/tmpfiles.d/libteam.conf
23+mkdir -p %{buildroot}%{_tmpfilesdir}
24+cat > %{buildroot}%{_tmpfilesdir}/libteam.conf <<EOF
25+# See tmpfiles.d(5) for details
26+# Type(d=directory) Path Mode UID GID Age(until delete when cleaning)
27+d %teamd_daemon_directory 0755 %teamd_user %teamd_group -
28+EOF
29+
```
Along with some other tmpfile config stuff and an additional [patch](https://build.opensuse.org/package/view_file/network/libteam/better_handle_failures_to_chown.patch?expand=1&rev=45a0febed1b33d2eb516646dcbc70154).

Thanks for also looking into this. Much appreciated.

**Comment by phillxnet** [comment]
Just noting that the indicated patch has a nice explanation and a link to it's in-turn upstream:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/722
