### ISSUE TITLE
Empty output from `myip` when network connection is unavailable

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-installer#96]
When the network connection is unavailable, the `myip` script does not return anything, which is not the most explicit. Maybe we could improve the user feedback by letting the user know that there was no IP to be returned, which is indicative of a network issue. See screenshot below:
![image](https://user-images.githubusercontent.com/30297881/152560441-11c230a2-b5d3-430c-9b45-4f95715abefe.png)

A comment in `myip` does indicate the desire to improve that script so addressing this issue could be done then.

PS: @phillxnet , note that this was seen in openQA ;)

**Comment by phillxnet** [comment]
Reproducer for this issue when an existing network connection does exist:
```
nmcli device disconnect eth0
myip

nmcli device connect eth0
myip
https://192.168.2.105
```
